<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
                <meta charset="utf-8"/>
                <link rel="stylesheet" type="text/css" href="../../../css/style.css"/>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>iift</title>
</head>
<body> <header>I quit working and not taking any engagements. this website isn't maintained anymore, links and pages are intentionally deleted.</header>
	<main> <nav> <details close="">
						<summary>Links</summary>
			.....................................
                        <ul>
                                <li><a href="../../../index.html">Home</a></li>
                                <li><a href="../../../about/index.html#info">About Me</a></li>
				<li><a href="../../../activism">Activism</a></li>
				<li><a href="../../../bookmarks">Bookmarks</a></li>
                                <li><a href="../../../econ">Books/Notes</a></li>
				<li><a href="../../../cs">coding style</a></li>
                                <li><a href="../../../resume">Resume</a></li>
                                <li><a href="../../../work/index.html#work">work with me</a></li>
                        .............................
                                <li><a href="../git">/git/</a>: packages</li>
				<li><a href="../dot"> /dot:files/ /scripts/</a></li>
                        </ul>
                        .....................................
		</details></nav>
	<themes><details close=""><summary>Themes&ensp;&ensp;&ensp;</summary>&ensp;<a href="index.x.html">plain HTML</a>&ensp;<br>&ensp;<a href="index.l.html">Light Mode</a></details></themes>
	</main>
	
		<section></section>
			
<main><details open=""> <summary>Videos</summary> <h3></h3>
	<div class="container">
	
		<table>
				<thead><tr><th>Date/Title</th><th>Micro</th><th>Macro</th><th>Maths</th><th>Ecotrix</th></tr></thead>
				<tbody>
<tr>
		<th>05 Oct</th>
		<td>
										<nav><details close="">
					<summary>MIE-10-05</summary>
				
						<ul>

						<a><details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/97f0b65c-c572-450a-acda-c63b5fc2d1a1-360.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/97f0b65c-c572-450a-acda-c63b5fc2d1a1-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		</td>
		<td>
										<nav><details close="">
					<summary>MAE-10-05</summary>
				
						<ul>
						
						<a><details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/b9f702ab-4b6f-4570-940d-5caff83c926f-360.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/b9f702ab-4b6f-4570-940d-5caff83c926f-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		
		</td>
		<td>
										<!--<nav><details close="">
					<summary>MHE-10-05</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCx" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUC3" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCY" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCg" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav> -->
		
		</td>
		<td>
										<nav><details close="">
					<summary>BE-10-05</summary>
				
						<ul>
						
						<a><details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/ff3eeda2-0420-480f-a22c-b4f36355194b-360.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/ff3eeda2-0420-480f-a22c-b4f36355194b-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		
		</td>
		
</tr>
						
<tr>
		<th>07 Oct</th>
		<td>
										<nav><details close="">
					<summary>MIE-10-07</summary>
				
						<ul>
						
						<a><details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/2bbb3de4-4d7f-44fe-9eed-2b9213ab512f-360.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/2bbb3de4-4d7f-44fe-9eed-2b9213ab512f-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		</td>
		<td>
										<nav><details close="">
					<summary>MAE-10-07</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/1a1af3b0-501d-40b4-8edf-03d9230c9239-240.mp4" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/1a1af3b0-501d-40b4-8edf-03d9230c9239-360.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/1a1af3b0-501d-40b4-8edf-03d9230c9239-480.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/1a1af3b0-501d-40b4-8edf-03d9230c9239-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
				</td>
		<td>
										<nav><details close="">
					<summary>MHE-10-07</summary>
				
						<ul>

						<a><details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/7e4bd645-5e1d-4118-9a0a-1b74465b9c4a-360.mp4" type="video/mp4"> </video>	
							</details>
												
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/7e4bd645-5e1d-4118-9a0a-1b74465b9c4a-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>


		</td>
		<td>  </td>

</tr>

<tr>
		<th>08 Oct</th>
		<td>
										<nav><details close="">
					<summary>MIE-10-08</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCx" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUC3" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCY" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCg" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>

		</td>
		<td>  </td>
		<td>
								<nav><details close="">
					<summary>MHE-10-08</summary>
				
						<ul>
						
						<a><details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/5fa4fb21-ebb5-49fb-8127-1af78409de61-360.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/5fa4fb21-ebb5-49fb-8127-1af78409de61-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		</td>
		<td>
									<!--	<nav><details close="">
					<summary>BE-10-08</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCx" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUC3" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCY" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUCg" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav> -->
		
		</td>
		<td>  </td>
		
</tr>

<!-- <tr>
		<th>11 Oct</th>
		<td>  </td>
		<td>  </td>
		<td>  </td>
		<td>  </td>
		<td>
								<nav><details close="">
					<summary>Placement-Cell Orientation</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUFu" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUFS" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUFQ" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/NUF1" type="video/mp4"> </video>	
						</details></a>
						
						
					</details></nav>

		</td>

</tr></td> -->


<tr>

		<th>18 Oct</th>
		<td>
								<nav><details close="">
					<summary>MIE-10-18-part1</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0rX" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0rH" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/N0ro" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/N0r-" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
									
					
																							
								<nav><details close="">
					<summary>MIE-10-18-part2</summary>
				
						<ul>
						
						<!--<a><details close="">  <summary>240</summary> <video id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0rX" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0rH" type="video/mp4"> </video>	
							</details> -->
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/N0ra" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/N0rm" type="video/mp4"> </video>	
						</details>
						
						<details close="">  <summary>1080</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://0x0.st/N0rA" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>

		</td>
		<td>
								<nav><details close="">
					<summary>MAE-10-18</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0rZ" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0rP" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0rK" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="http://0x0.st/N0r8" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>

		</td>
		<td>  </td>
		<td>  </td>
</tr>


<tr>

		<th>21 Oct</th>
		<td>  </td>
		<td>
										<nav><details close="">
					<summary>MAE-10-21</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/14c3ae35-d229-4ef6-af29-d7fd1212e5a9-240.mkv" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/14c3ae35-d229-4ef6-af29-d7fd1212e5a9-360.mkv" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/14c3ae35-d229-4ef6-af29-d7fd1212e5a9-480.mkv" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/14c3ae35-d229-4ef6-af29-d7fd1212e5a9-720.mkv" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		</td>
		<td>
												<nav><details close="">
					<summary>MHE-10-21</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/95fe3119-6157-4cbd-8317-ab95e81f7a59-240.mkv" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/95fe3119-6157-4cbd-8317-ab95e81f7a59-360.mkv" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/95fe3119-6157-4cbd-8317-ab95e81f7a59-480.mkv" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tubedu.org/download/videos/95fe3119-6157-4cbd-8317-ab95e81f7a59-720.mkv" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>

		</td>
		<td>
										<nav><details close="">
					<summary>BE-10-21</summary>
				
						<ul>
						
						<a><details close="">  <summary>240</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/2eced5f6-8064-46b4-bddf-2876e6997289-240.mp4" type="video/mp4"> </video>
							</details>

						<details close="">  <summary>360</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/2eced5f6-8064-46b4-bddf-2876e6997289-360.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/2eced5f6-8064-46b4-bddf-2876e6997289-480.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://devtube.dev-wiki.de/download/videos/2eced5f6-8064-46b4-bddf-2876e6997289-720.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		</td>
</tr>
<tr>
		<th>25 Oct</th>
		<td>
										<nav><details close="">
					<summary>MIE-10-25</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/9fa7dc84-31f2-4548-b271-7319c957c941-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/9fa7dc84-31f2-4548-b271-7319c957c941-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		</td>
		<td>
										<nav><details close="">
					<summary>MAE-10-25-part1</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/44425915-08bb-42a9-a12e-98ea00cfcc6a-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/44425915-08bb-42a9-a12e-98ea00cfcc6a-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
											<nav><details close="">
					<summary>MAE-10-25-part2</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/df8c4a5e-d6e9-47d1-a597-87720471bb72-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/df8c4a5e-d6e9-47d1-a597-87720471bb72-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
	
		</td>  <td>
		</td>  <td>

</tr>
<tr>
		<th>26 Oct</th>
		<td>
										<nav><details close="">
					<summary>MIE-10-26</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/b912150f-7913-4205-8ae9-7de4de8c5b90-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>

						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/b912150f-7913-4205-8ae9-7de4de8c5b90-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		</td>
		<td>
										<nav><details close="">
					<summary>MAE-10-26</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/aa62cb46-ea95-4d08-b054-c8228c5fba31-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>

						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/aa62cb46-ea95-4d08-b054-c8228c5fba31-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		
		</td>
		</td>  <td>
		<td>
										<nav><details close="">
					<summary>BE-10-26</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/49b75b1b-a9a5-45e9-b6d2-7f84985e0135-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/49b75b1b-a9a5-45e9-b6d2-7f84985e0135-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
				
		<td>

</tr>


<tr>
		<th>28 Oct</th>
		<td>  </td>
		<td>
										<nav><details close="">
					<summary>MAE-10-28-part1</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/f037b755-d75d-43ae-8675-8c8d173db855-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>

						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/f037b755-d75d-43ae-8675-8c8d173db855-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
					
										<nav><details close="">
					<summary>MAE-10-28-part2</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/1334bec1-c0f3-439a-b294-6b729bf86e70-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>

						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/1334bec1-c0f3-439a-b294-6b729bf86e70-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		
		</td>
		<td>
		
										<nav><details close="">
					<summary>MHE-10-28</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/000114f1-55c1-41a3-b550-400c73dfd85f-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>

						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/000114f1-55c1-41a3-b550-400c73dfd85f-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		
		</td>
		<td>
										<nav><details close="">
					<summary>BE-10-28</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/0b99b7e7-227c-4d85-93e6-4818d747484a-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>
						
						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/0b99b7e7-227c-4d85-93e6-4818d747484a-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
				
		<td>

</tr>

<tr>
		<th>29 Oct</th>
		<td>
										<nav><details close="">
					<summary>MIE-10-29</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/bb48779f-7459-4c90-90a0-e939d9c2c50a-720-fragmented.mp4" type="video/mp4"> </video>	
							</details>

						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/bb48779f-7459-4c90-90a0-e939d9c2c50a-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
							
		</td>
		<td>  </td>
		<td>
		
										<nav><details close="">
					<summary>MHE-10-29</summary>
				
						<ul>
						
						<a><details close="">  <summary>480</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/70606201-936d-4886-9915-b1e7b094a03c-480-fragmented.mp4" type="video/mp4"> </video>	
							</details>

						<details close="">  <summary>720</summary> <video oncontextmenu="return false;" id="my-video-player" width="100%" height="100%" controls preload="none"> <source src="https://tube.tchncs.de/download/streaming-playlists/hls/videos/70606201-936d-4886-9915-b1e7b094a03c-720-fragmented.mp4" type="video/mp4"> </video>	
						</details></a>
						
						</ul>
						
					</details></nav>
		
		</td>
		<td></td>

</tr>


				</tbody> </table>
				</div>
				


</details></main>


  <footer>
	<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img loading="lazy" alt="CC-BY-SA" src="https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/by-sa.svg" /></a>
  </footer>
 </body>
</html>
